import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'マクロ栄養計算',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className='bg-black text-white'>{children}</body>
    </html>
  );
}
